import Head from 'next/head';
import Image from 'next/image';
import Skeleton from 'react-loading-skeleton';
import axios from 'axios';

import Paw from '../public/paw.svg';
import Search from '../public/search.svg';

export default function Home(props: any) {
  return (
    <>
      <Head>
        <title>Home - Dog Wiki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <section className="rounded-t-large bg-hero-color flex justify-between">
          <section className="flex flex-col flex-shrink justify-center text-white pl-6 pr-2 pb-12 pt-7 md:pl-20">
            <div className="flex items-center">
              <span className="text-3xl md:text-5xl font-cursive mr-5">DogWiki</span>
              <Paw className="w-16 hidden md:block" />
            </div>

            <p className="mt-7 mb-10 text-xl">Get to know more about your dog breed</p>

            <div className="bg-white flex items-center rounded-large2 px-5 py-3">
              <input
                className="focus:outline-none flex-grow w-16 min-w-heroImg px-4 py-1 rounded-inherit text-black"
                placeholder="Search"
              />
              <Search className="w-6" />
            </div>
          </section>

          <img
            className="flex-grow-0 object-cover max-w-heroImg min-w-heroImg rounded-tr-large"
            src="/hero.jpg"
            alt=""
          />
        </section>

        <section className="rounded-b-large bg-hero-down px-6 md:px-20 pt-10 pb-10">
          <h2 className="inline-block text-primary text-lg">Most Searched Breeds</h2>
          <div className="bg-mud rounded-3xl max-w-tiny p-tiny"></div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <h2 className="max-w-breed mt-10 font-semibold text-primary text-4xl">
              99+ Breeds for you to discover
            </h2>

            <div className="flex items-end sm:justify-end text-enamel whitespace-nowrap">
              <span className="font-semibold uppercase">see more</span>
              <span className="ml-2">&rarr;</span>
            </div>
          </div>

          <section className="grid grid-cols-175 gap-x-6 pt-14">
            {props.data.map((item: any) => (
              <div className="flex flex-col" key={item.id}>
                <img className="!rounded-3xl h-48 object-cover" src={item.image.url} />
                <p className="text-primary mt-3 font-semibold text-lg">{item.name}</p>
              </div>
            ))}
          </section>
        </section>
      </main>

      <section className="container mt-24">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="">
            <div className="bg-mud rounded-3xl max-w-tiny p-tiny"></div>
            <h2 className="mt-6 text-5xl font-bold max-w-lg leading-tight text-primary">
              Why should you have a dog?
            </h2>
            <p className="text-lg font-normal mt-8 max-w-lg opacity-80">
              Having a dog around you can actually trigger the release of calming
              chemicals in your body which lower your stress and anxiety leves
            </p>
            <div className="mt-8 text-enamel">
              <span className="font-semibold  uppercase">read more</span>
              <span className=" ml-2">&rarr;</span>
            </div>
          </div>
          <div className="grid grid-cols-2 grid-rows-2 gap-5 h-[28rem] md:h-[35rem]">
            <img
              className="h-full object-cover rounded-3xl"
              src="/playwithme.jpg"
              alt=""
            />

            <img
              className="rounded-3xl h-full object-cover row-span-2"
              src="/puppies.jpg"
            />

            <img
              className="rounded-3xl h-full w-full object-cover"
              src="/cooldog.jpg"
              alt=""
            />
          </div>
        </div>
      </section>
    </>
  );
}

export async function getServerSideProps() {
  const response = await axios.get('https://api.thedogapi.com/v1/breeds?limit=4', {
    headers: { 'x-api-key': process.env.DOG_API_KEY },
  });

  return {
    props: { data: response.data },
  };
}
